### let's first check which images we want to avoid

In [38]:
import os
import pandas as pd
import numpy as np
import time

In [2]:
path = "../data/train_sample/"

In [3]:
files = [x for x in os.listdir(path) if x[-3:] == 'jpg']

In [4]:
len(files)

10000

In [7]:
labels_file =  "../data/labels/boxes_v2.csv"
y_raw = pd.read_csv(labels_file)

In [8]:
y_raw.head(1)

ImageId  width  height  lt_x  lt_y  rb_x  rb_y
0  00003e153.jpg      0       0     0     0     0     0

In [18]:
all_imgs = list(y_raw.ImageId)

In [19]:
startTime = time.time()
for i in range(len(files)):
    all_imgs.remove(files[i])
print("time:",time.time()-startTime)

time: 25.100682020187378


In [20]:
idx = np.random.choice(len(all_imgs), 100)
test_imgs = [all_imgs[i] for i in idx]

In [24]:
len(test_imgs[0])

13

In [25]:
np.savetxt("/Users/margheritarosnati/Documents/DS/2018-2/DL/DeepBlueSea/test_imgs_list.csv",
           np.asarray(test_imgs),
           fmt='%15s', 
           delimiter=';')

In [26]:
n=2
idx = np.random.choice(len(files), n)
test_of_test = [files[i] for i in idx]
print(test_of_test)

['2b41fd0e8.jpg', '2bba22a59.jpg']


In [28]:
part = "/Users/margheritarosnati/Documents/"
i=4
part + str(i)

'/Users/margheritarosnati/Documents/4'

# Boxes proposal

In [ ]:
path ="/Users/margheritarosnati/Desktop/"
class_score = np.load(path+'class_score.npy')
reg_score = np.load(path+'reg_score.npy')

In [2]:
import numpy as np

In [128]:
print(boxes_per_image(class_score[0], reg_score[0], class_thres= 0.57, debug=1))

num of pos anchors: 23
[[ -3   9 532 545]
 [651 668 426 443]
 [651 668 425 442]
 [547 560 405 420]
 [545 560 405 420]
 [546 561 404 419]
 [545 560 404 419]
 [342 357 335 350]
 [341 356 336 349]
 [342 357 334 349]]
